NAME = libft.a
SRC = ft_atoi.c \
      ft_bzero.c \
      ft_calloc.c \
      ft_isalnum.c \
      ft_isalpha.c \
      ft_isascii.c \
      ft_isdigit.c \
      ft_isprint.c \
      ft_itoa.c \
      ft_memchr.c \
      ft_memcmp.c \
      ft_memcpy.c \
      ft_memmove.c \
      ft_memset.c \
      ft_putchar_fd.c \
      ft_putendl_fd.c \
      ft_putnbr_fd.c \
      ft_putstr_fd.c \
      ft_split.c \
      ft_strchr.c \
      ft_strdup.c \
      ft_striteri.c \
      ft_strjoin.c \
      ft_strlcat.c \
      ft_strlcpy.c \
      ft_strlen.c \
      ft_strmapi.c \
      ft_strncmp.c \
      ft_strnstr.c \
      ft_strrchr.c \
      ft_strtrim.c \
      ft_substr.c \
      ft_tolower.c \
      ft_toupper.c \
      ft_printf.c \
      ft_printf_utils.c \
      ft_printf_utils_convert.c \
      ft_ptr.c \
      ft_hex.c \
      ft_realloc.c \
	ft_utoa.c \
      ft_fperror.c \
      get_next_line.c \
      get_next_line_utils.c \
      ft_isspace.c \
      ft_puterror.c \
      ft_putgood.c \

OBJ = $(SRC:.c=.o)

CC = clang
CFLAGS = -Wall -Wextra -Werror

all: $(NAME)

$(NAME): $(OBJ)
	$(CC) $(CFLAGS) -c $(SRC)
	ar rcs $(NAME) $(OBJ)

clean:
	/bin/rm -f $(OBJ) libft.so

fclean: clean
	/bin/rm -f $(NAME)

re: fclean all

so: $(SRC)
	$(CC) $(CFLAGS) -fPIC -c $(SRC)
	$(CC) -shared -o libft.so $(OBJ)

.PHONY: all clean fclean re so

